import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

/*
 * `eslint-config-next` still ships as an eslintrc config, so FlatCompat is what
 * bridges it into ESLint 9's flat format. This is the shape create-next-app
 * generates; it replaces the deprecated `next lint`, which ran nothing here.
 */
const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "out/**",
      "node_modules/**",
      // Agent worktrees: copies of the repo, linted at their own root.
      ".claude/**",
      // Video source projects, not site code.
      "components/videos/**",
      "public/**",
      // Generated by Next on every build; its triple-slash refs are intentional.
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      /*
       * `output: "export"` requires `images.unoptimized`, so next/image would emit
       * the identical raw file and optimize nothing — and the sizing here (an
       * overflow crop at width 270%, a marquee sized w-auto off its height) is not
       * expressible through it. Raw <img> is the deliberate choice site-wide.
       */
      "@next/next/no-img-element": "off",
    },
  },
];

export default eslintConfig;
